---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 1h
  url: https://charts.jetstack.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace:  cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      interval: 10m
  values: # https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
    installCRDs: false
