---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 1h
  url: https://charts.jetstack.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace:  cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      interval: 10m
  values: # https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
    installCRDs: true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: jamespaulmoriarty+letsencrypt@gmail.com
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    privateKeySecretRef:
      name: letsencrypt-secret
    solvers:
    - dns01:
        route53:
          region: ap-southeast-2
          accessKeyID: AKIAWZSIWZIEAJ4HUDGA
          hostedZoneID: Z0933032X41CPGT2FY5A
          secretAccessKeySecretRef:
            name: cert-manager
            key: AWS_SECRET_ACCESS_KEY