---
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  EXTERNAL_DNS_DOMAIN_FILTER: # home.jamesmoriarty.xyz
  EXTERNAL_DNS_TXT_OWNER_ID: # Z093303...
kind: Secret
metadata:
  name: external-dns
  namespace: default
---
apiVersion: v1
data:
  address: # 'https://hooks.slack.com/services/.../.../...'
kind: Secret
metadata:
  name: slack-url
  namespace: flux-system
type: Opaque
---
apiVersion: v1
data:
  values.yaml:
  # alertmanager:
  #   config:
  #     global:
  #       slack_api_url: 'https://hooks.slack.com/services/.../.../...'
kind: Secret
metadata:
  name: alertmanager
  namespace: monitoring
