---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exposure-bot
  name: exposure-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exposure-bot
  template:
    metadata:
      labels:
        app: exposure-bot
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: database
        hostPath:
          path: /var/k8s-gitops/
          type: Directory
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
      - image: ghcr.io/jamesmoriarty/victoria-exposure-site-bot:0.0.5
        name: exposure-bot
        command: 
        - /bin/sh
        - -c
        - exposure-bot --csv-url=$CSV_URL --slack-url=$SLACK_URL --database=$DATABASE
        env:
        - name: SLACK_URL
          valueFrom:
            secretKeyRef:
              name: exposure-bot
              key: slack-url
        - name: CSV_URL
          value: https://docs.google.com/spreadsheets/d/e/2PACX-1vSNouXrJ8UQ-tn6bAxzrOdLINuoOtn01fSjooql0O3XQlj4_ldFiglzOmDm--t2jy1k-ABK6LMzPScs/pub?gid=1075463302&single=true&output=csv
        - name: DATABASE
          value: tmp/victoria-exposure-site-bot.db
        volumeMounts:
        - mountPath: /usr/src/app/tmp
          name: database
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "100m"
