apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k8s-gitops-example-app
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/jamesmoriarty/k8s-gitops-example-app
  secretRef:
    name: flux-system
