---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cilium
  namespace: network
spec:
  interval: 1h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace:  network
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.9.3
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: cilium
      interval: 10m
      valuesFile: values.yaml