apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k8s-gitops-example-app
  namespace: default
spec:
  interval: 1m
  url: https://github.com/jamesmoriarty/k8s-gitops-example-app