apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ip
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ip
            image: bitnami/kubectl
            command:
            - /bin/sh
            - -c
            - |
              cat << EOF > /tmp/service.yml && kubectl apply -f /tmp/service.yml
              apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: nginx
                annotations:
                  kubernetes.io/ingress.class: nginx
                  external-dns.alpha.kubernetes.io/hostname: '$IP_HOSTNAME'
                  external-dns.alpha.kubernetes.io/target: '$(curl --silent ifconfig.me)'
              spec:
                rules:
                - host: ip.home.jamesmoriarty.xyz
              EOF
            env:
            - name: IP_HOSTNAME
              value: ip.home.jamesmoriarty.xyz
          restartPolicy: OnFailure