apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ip
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ip
            image: bitnami/kubectl
            command:
            - /bin/sh
            - -c
            - |
              cat << EOF > /tmp/service.yml && kubectl apply -f /tmp/service.yml
              apiVersion: v1
              kind: Service
              metadata:
                name: ip
                annotations:
                  external-dns.alpha.kubernetes.io/hostname: '$IP_HOSTNAME'
                  external-dns.alpha.kubernetes.io/target: '$(curl --silent ifconfig.me)'
              spec:
                selector:
                  app: supercalifragilisticexpialidocious
                ports:
                - protocol: TCP
                  port: 8080
                  targetPort: 8080
              EOF
            env:
            - name: IP_HOSTNAME
              value: ip.home.jamesmoriarty.xyz
          restartPolicy: OnFailure