apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jackett
  name: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - image: ghcr.io/linuxserver/jackett
        name: jackett
        ports:
        - containerPort: 9117
