apiVersion: v1
kind: Service
metadata:
  name: jackett
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "jackett.home.jamesmoriarty.xyz"
spec:
  type: LoadBalancer
  selector:
    app: jackett
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9117