apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minidlna
  name: minidlna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minidlna
  template:
    metadata:
      labels:
        app: minidlna
    spec:
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: downloads
          hostPath:
            path: /var/hombernetes/downloads
            type: Directory
      containers:
      - image: vladgh/minidlna
        name: minidlna
        ports:
        - containerPort: 8020
          protocol: TCP
        - containerPort: 1900
          protocol: UDP
        env:
        - name: MINIDLNA_MEDIA_DIR
          value: /downloads
        volumeMounts:
        - mountPath: /downloads
          name: downloads
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 8020
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          tcpSocket:
            port: 8020
          timeoutSeconds: 2