apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: downloads
          hostPath:
            path: /var/hombernetes/downloads
            type: Directory
      containers:
      - image: ghcr.io/linuxserver/radarr
        name: radarr
        ports:
        - containerPort: 7878
        volumeMounts:
        - mountPath: /downloads
          name: downloads
