apiVersion: v1
kind: Service
metadata:
  name: radarr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "radarr.home.jamesmoriarty.xyz"
spec:
  type: LoadBalancer
  selector:
    app: radarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7878