apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minidlna
  name: minidlna
spec:
  replicas: 1
  # N.B. required to avoid hostNetwork single node port conflict.
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minidlna
  template:
    metadata:
      labels:
        app: minidlna
    spec:
      # N.B. The uPnP UDP broadcast’s are coming from the pod’s internal address are being dropped by the node before it egresses into your home network. 
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: downloads
          hostPath:
            path: /var/hombernetes/downloads
            type: Directory
      containers:
      - image: vladgh/minidlna
        name: minidlna
        ports:
        - containerPort: 8020
          protocol: TCP
        - containerPort: 1900
          protocol: UDP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            drop:
            - ALL
          readOnlyRootFilesystem: false
        env:
        - name: MINIDLNA_FRIENDLY_NAME
          value: hombernetes
        - name: MINIDLNA_MEDIA_DIR
          value: /downloads
        volumeMounts:
        - mountPath: /downloads
          name: downloads