# kubectl exec -n kube-system -t ds/cilium -- hubble observe
# kubectl exec -n kube-system -t ds/cilium -- hubble observe -t drop --follow
#
# kubectl exec -n kube-system -t ds/cilium -- cilium status
# kubectl exec -n kube-system -t ds/cilium -- cilium bpf tunnel list
#
# kubectl exec -n kube-system -t ds/cilium -- cilium-bugtool
# kubectl cp kube-system/cilium-kg8lv:/tmp/cilium-bugtool-20180411-155146.166+0000-UTC-266836983.tar /tmp/cilium-bugtool-20180411-155146.166+0000-UTC-266836983.tar

ipam:
  # -- Configure IP Address Management mode.
  # ref: https://docs.cilium.io/en/stable/concepts/networking/ipam/
  mode: "cluster-pool"
  operator:
    # -- IPv4 CIDR range to delegate to individual nodes for IPAM.
    clusterPoolIPv4PodCIDR: "192.168.0.0/16"
    # -- IPv4 CIDR mask size to delegate to individual nodes for IPAM.
    clusterPoolIPv4MaskSize: 24

monitor:
  enabled: true

prometheus:
  enabled: true

hubble:
  enabled: true
  listenAddress: '10.0.0.238:4244'
  metrics:
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - icmp
    - http
  relay:
    enabled: true
  ui:
    enabled: true

operator:
  replicas: 1
  prometheus:
    enabled: true
