---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: falcosecurity
  namespace: security
spec:
  interval: 30m
  url: https://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: falco
      version: 1.7.10
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: security
      interval: 5m
  values: # https://github.com/falcosecurity/charts/blob/master/falco/values.yaml
    logLevel: error
    containerd:
      enabled: true
      socket: /var/run/k3s/containerd/containerd.sock
    docker:
      enabled: false
    ebpf:
      enabled: true
      settings:
        hostNetwork: true
    falco:
      grpc:
        enabled: true
      grpcOutput:
        enabled: true
    rules-ssh-connections.yaml: |-
      - rule: Inbound SSH Connection
        desc: Detect Inbound SSH Connection
        condition: >
          ((evt.type in (accept,listen) and evt.dir=<) or
            (evt.type in (recvfrom,recvmsg))) and ssh_port
        output: >
          Inbound SSH connection (user=%user.name client_ip=%fd.cip client_port=%fd.cport server_ip=%fd.sip)
        priority: WARNING
        tags: [network]
      - rule: Outbound SSH Connection
        desc: Detect Outbound SSH Connection
        condition: >
          ((evt.type = connect and evt.dir=<) or
            (evt.type in (sendto,sendmsg))) and ssh_port
        output: >
          Outbound SSH connection (user=%user.name server_ip=%fd.sip server_port=%fd.sport client_ip=%fd.cip)
        priority: WARNING
        tags: [network]
    falcosidekick:
      enabled: true
      config: # https://github.com/falcosecurity/charts/blob/master/falcosidekick/values.yaml
        alertmanager:
          hostport: "http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093"
          minimumpriority: "none"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco-exporter
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: falco-exporter
      version: 0.5.1
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: security
      interval: 5m
  values:
    serviceMonitor:
      enabled: true
     