

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: falcosecurity
  namespace: security
spec:
  interval: 30m
  url: https://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: falco
      version: 1.7.10
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: security
      interval: 5m
  values: # https://github.com/falcosecurity/charts/blob/master/falco/values.yaml
    falcosidekick:
      enabled: true
      # https://github.com/falcosecurity/charts/blob/master/falcosidekick/values.yaml
      replicaCount: 1