apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '12.2.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m

  values: # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
    kubeControllerManager:
      enabled: false

    kubeScheduler:
      enabled: false

    alertmanager:
      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ['job']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: 'slack-notifications'
          routes:
          - receiver: 'null'
            match:
              alertname: Watchdog
        receivers:
        - name: 'null'
        - name: 'slack-notifications'
          slack_configs:
          - channel: '#k8s-gitops'
            send_resolved: true
      alertmanagerSpec:
        externalUrl: 'http://alertmanager.home.jamesmoriarty.xyz:9093/'
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "alertmanager.home.jamesmoriarty.xyz"
        type: LoadBalancer

    grafana:
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "grafana.home.jamesmoriarty.xyz"
        type: LoadBalancer

    prometheus:
      prometheusSpec:
        externalUrl: 'http://prometheus.home.jamesmoriarty.xyz:9090/'
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "prometheus.home.jamesmoriarty.xyz"
        type: LoadBalancer

  valuesFrom:
  - secretFileRef:
    kind: Secret
    name: alertmanager