---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 30m
  url: https://grafana.github.io/loki/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: '2.0.3'
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: monitoring
      interval: 10m