apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '12.1.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    grafana:
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "grafana.home.jamesmoriarty.xyz"
        type: LoadBalancer
    prometheus:
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "prometheus.home.jamesmoriarty.xyz"
        type: LoadBalancer