---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: default
spec:
  interval: 30m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: default
spec:
  interval: 2m
  chart:
    spec:
      chart: external-dns
      version: '4.3.1'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 2m
    
  values: # https://github.com/bitnami/charts/blob/master/bitnami/external-dns/values.yaml
    metrics:
      enabled: true
    extraEnv:
      - name: EXTERNAL_DNS_DOMAIN_FILTER
        valueFrom:
          secretKeyRef:
            name: external-dns
            key: EXTERNAL_DNS_DOMAIN_FILTER
      - name: EXTERNAL_DNS_TXT_OWNER_ID
        valueFrom:
          secretKeyRef:
            name: external-dns
            key: EXTERNAL_DNS_TXT_OWNER_ID
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: external-dns
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns
            key: AWS_SECRET_ACCESS_KEY
